var arrTabList = ['recommend', 'hamburger', 'side', 'drink', 'season'];

// 0: 추천, 1: 햄버거, 2: 사이드, 3: 음료수, 4: 시즌메뉴
var itemList = [
    '[{"index" : "1", "src" : "recommend/1.jpg", "name" : "모닝번", "price" : "4500원", "type": "recommend"},{"index" : "2", "src" : "recommend/2.jpg", "name" : "밀크쉐이크", "price" : "4500원", "type": "recommend"},{"index" : "3", "src" : "recommend/3.jpg", "name" : "불고기 버거", "price" : "5500원", "type": "recommend"},{"index" : "4", "src" : "recommend/4.jpg", "name" : "핫스파이시 버거", "price" : "6000원", "type": "recommend"},{"index" : "5", "src" : "recommend/5.jpg", "name" : "치킨텐더", "price" : "2800원", "type": "recommend"},{"index" : "6", "src" : "recommend/6.jpg", "name" : "코카콜라 제로", "price" : "2000원", "type": "recommend"},{"index" : "7", "src" : "recommend/7.jpg", "name" : "팥빙수", "price" : "7000원", "type": "recommend"}]',
    '[{"index" : "1", "src" : "hamburger/1.jpg", "name" : "모닝번", "price" : "4500원", "type": "hamburger"},{"index" : "2", "src" : "hamburger/2.jpg", "name" : "베이컨 불고기 버거", "price" : "6,500원", "type": "hamburger"},{"index" : "3", "src" : "hamburger/3.jpg", "name" : "베이컨 새우 버거", "price" : "6,700원", "type": "hamburger"},{"index" : "4", "src" : "hamburger/4.jpg", "name" : "불고기 버거", "price" : "5500원", "type": "hamburger"},{"index" : "5", "src" : "hamburger/5.jpg", "name" : "불고기 치즈 버거", "price" : "5700원", "type": "hamburger"},{"index" : "6", "src" : "hamburger/6.jpg", "name" : "새우 버거", "price" : "4800원", "type": "hamburger"},{"index" : "7", "src" : "hamburger/7.jpg", "name" : "에그포테이토 버거", "price" : "4200원", "type": "hamburger"},{"index" : "8", "src" : "hamburger/8.jpg", "name" : "치즈 버거", "price" : "3500원", "type": "hamburger"},{"index" : "9", "src" : "hamburger/9.jpg", "name" : "치즈 포테이토 버거", "price" : "5000원", "type": "hamburger"},{"index" : "10", "src" : "hamburger/10.jpg", "name" : "토마토 디럭스 버거", "price" : "5700원", "type": "hamburger"},{"index" : "11", "src" : "hamburger/11.jpg", "name" : "페퍼로니 버거", "price" : "7500원", "type": "hamburger"},{"index" : "12", "src" : "hamburger/12.jpg", "name" : "핫스파이시 버거", "price" : "6000원", "type": "hamburger"}]',
    '[{"index" : "1", "src" : "side/1.jpg", "name" : "감자튀김", "price" : "2000원", "type": "side"},{"index" : "2", "src" : "side/2.jpg", "name" : "양념감자", "price" : "2500원", "type": "side"},{"index" : "3", "src" : "side/3.jpg", "name" : "웨지감자", "price" : "2000원", "type": "side"},{"index" : "4", "src" : "side/4.jpg", "name" : "체다치즈 감자튀김", "price" : "3000원", "type": "side"},{"index" : "5", "src" : "side/5.jpg", "name" : "치즈스틱", "price" : "2300원", "type": "side"},{"index" : "6", "src" : "side/6.jpg", "name" : "롱치즈스틱", "price" : "2800원", "type": "side"},{"index" : "7", "src" : "side/7.jpg", "name" : "바닐라 아이스크림", "price" : "1500원", "type": "side"},{"index" : "8", "src" : "side/8.jpg", "name" : "초코 아이스크림", "price" : "2000원", "type": "side"},{"index" : "9", "src" : "side/9.jpg", "name" : "치킨윙", "price" : "3500원", "type": "side"},{"index" : "10", "src" : "side/10.jpg", "name" : "치킨텐더", "price" : "2800원", "type": "side"}]',
    '[{"index" : "1", "src" : "drink/1.jpg", "name" : "코카콜라", "price" : "2000원", "type": "drink"},{"index" : "2", "src" : "drink/2.jpg", "name" : "코카콜라 제로", "price" : "2000원", "type": "drink"},{"index" : "3", "src" : "drink/3.jpg", "name" : "펩시 제로", "price" : "2000원", "type": "drink"},{"index" : "4", "src" : "drink/4.jpg", "name" : "환타", "price" : "2000원", "type": "drink"},{"index" : "5", "src" : "drink/5.jpg", "name" : "사이다", "price" : "2000원", "type": "drink"},{"index" : "6", "src" : "drink/6.jpg", "name" : "스프라이트", "price" : "2000원", "type": "drink"},{"index" : "7", "src" : "drink/7.jpg", "name" : "밀크쉐이크", "price" : "4500원", "type": "drink"}]',
    '[{"index" : "1", "src" : "season/1.jpg", "name" : "산딸기차", "price" : "3500원", "type": "season"},{"index" : "2", "src" : "season/2.jpg", "name" : "오미자차", "price" : "3500원", "type": "season"},{"index" : "3", "src" : "season/3.jpg", "name" : "유자차", "price" : "3500원", "type": "season"},{"index" : "4", "src" : "season/4.jpg", "name" : "초코빙수", "price" : "7500원", "type": "season"},{"index" : "5", "src" : "season/5.jpg", "name" : "팥빙수", "price" : "7000원", "type": "season"}]'
];

